version: '3'
services:
  db:
    build: ./db
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  web:
      build: ./web
      ports:
        - '12711:80'
      volumes:
        - ./web/html:/var/www/html
      depends_on:
        - db